'use strict';
const $=id=>document.getElementById(id), canvas=$('course'),ctx=canvas.getContext('2d');
const V={add:(a,b)=>[a[0]+b[0],a[1]+b[1]],sub:(a,b)=>[a[0]-b[0],a[1]-b[1]],mul:(a,s)=>[a[0]*s,a[1]*s],len:a=>Math.hypot(...a),dist:(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]),mix:(a,b,t)=>[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t]};
const CLUBS=[{name:'Driver',max:260,loft:55},{name:'3 Wood',max:225,loft:48},{name:'5 Iron',max:180,loft:62},{name:'7 Iron',max:150,loft:74},{name:'9 Iron',max:120,loft:82},{name:'Wedge',max:75,loft:90},{name:'Putter',max:30,loft:0}];
const segDist=(p,a,b)=>{const ab=V.sub(b,a),d=ab[0]**2+ab[1]**2;const t=d?Math.max(0,Math.min(1,((p[0]-a[0])*ab[0]+(p[1]-a[1])*ab[1])/d)):0;return V.dist(p,V.mix(a,b,t));};
const river=[[-170,735],[-30,737],[105,738],[275,697],[425,647],[555,582],[690,502],[836,421],[875,327],[845,215],[731,85],[615,25],[518,12]];
HOLES.forEach((h,i)=>{h.mid=V.mix(h.tee,h.green,.52);if(i===1)h.mid=V.add(h.mid,[15,-8]);if(i===6)h.mid=V.add(h.mid,[-15,-12]);h.path=[h.tee,h.mid,h.green];const d=V.sub(h.green,h.tee),len=V.len(d);h.unit=V.mul(d,1/len);h.side=[-h.unit[1],h.unit[0]];h.bunkers=[{p:V.add(V.add(h.green,V.mul(h.side,17)),V.mul(h.unit,-6)),rx:7,ry:11,angle:Math.atan2(d[1],d[0])},{p:V.add(V.add(h.green,V.mul(h.side,-16)),V.mul(h.unit,5)),rx:6,ry:8,angle:Math.atan2(d[1],d[0])+.3}];});
const greenAt=p=>HOLES.find(h=>V.dist(p,h.green)<13);
const fairwayDist=p=>Math.min(...HOLES.flatMap(h=>[segDist(p,h.tee,h.mid),segDist(p,h.mid,h.green)]));
function inBunker(p,b){const d=V.sub(p,b.p),c=Math.cos(b.angle),s=Math.sin(b.angle);return ((d[0]*c+d[1]*s)/b.rx)**2+((-d[0]*s+d[1]*c)/b.ry)**2<1;}
function lieAt(p){if(p[0]<-110||p[0]>960||p[1]<-65||p[1]>790)return 'Out of bounds';if(river.some((a,i)=>i&&segDist(p,river[i-1],a)<10))return 'Water';if(HOLES.some(h=>h.bunkers.some(b=>inBunker(p,b))))return 'Bunker';if(greenAt(p))return 'Green';if(HOLES.some(h=>V.dist(p,h.tee)<8))return 'Tee box';return fairwayDist(p)<19?'Fairway':'Rough';}
let seed=1927;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const trees=[];for(let i=0;i<2600&&trees.length<235;i++){let p=[-60+rand()*980,40+rand()*690];let fd=fairwayDist(p);if(fd>26&&fd<56&&lieAt(p)!=='Water'&&!HOLES.some(h=>V.dist(p,h.green)<26)&&!trees.some(t=>V.dist(p,t.p)<11))trees.push({p,r:5+rand()*4,tall:rand()>.5,color:rand()});}
const grass=Array.from({length:1200},()=>({p:[-400+rand()*1800,-400+rand()*1700],r:.3+rand()*.6}));
let state={hole:0,ball:[...HOLES[0].tee],strokes:0,scores:Array(9).fill(null),club:0,power:95,angle:Math.atan2(HOLES[0].green[1]-HOLES[0].tee[1],HOLES[0].green[0]-HOLES[0].tee[0]),points:0};
try{const old=JSON.parse(localStorage.getItem('colfax-round-v1'));if(old&&Number.isInteger(old.hole)&&old.hole>=0&&old.hole<9&&Array.isArray(old.ball)&&old.ball.length===2&&old.ball.every(Number.isFinite)&&old.scores?.length===9&&old.scores.every(x=>x===null||Number.isInteger(x)))state={...state,...old};}catch{}
let w=0,h=0,dpr=1,phase='aim',needle=.5,needleDirection=1,animation=null,trail=[],overview=false,sound=false,audioCtx=null,camera=null,lastTime=0,toastUntil=performance.now()+7000,shotResult='';
const current=()=>HOLES[state.hole];const distance=()=>V.dist(state.ball,current().green);const scoreText=n=>n===0?'E':n>0?'+'+n:String(n);const toPar=()=>state.scores.reduce((sum,n,i)=>sum+(n===null?0:n-HOLES[i].par),0);
function save(){try{localStorage.setItem('colfax-round-v1',JSON.stringify(state));}catch{}}
function toast(msg,duration=3500){$('toast').textContent=msg;$('toast').style.opacity='1';toastUntil=performance.now()+duration;}
function beep(freq=450,dur=.08){if(!sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audioCtx.currentTime);g.gain.setValueAtTime(.10,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur);}catch{}}
function factor(){const lie=lieAt(state.ball);return lie==='Bunker'?(state.club===5?.8:.45):lie==='Rough'?(state.club===6?.32:.78):1;}
function expected(){return CLUBS[state.club].max*state.power/100*factor();}
function wind(){return {x:Math.sin(state.hole*1.7+.6)*3.5,y:Math.cos(state.hole*2.1+.5)*2.5};}
function sync(){const hole=current();$('hole').textContent=String(state.hole+1).padStart(2,'0');$('par').textContent=hole.par;$('yardage').textContent=hole.yards;$('total').textContent=scoreText(toPar());$('shot-count').textContent='SHOT '+(state.strokes+1);$('progress').innerHTML=HOLES.map((_,i)=>'<i class="'+(i<=state.hole?'active':'')+'"></i>').join('');$('lie').textContent=lieAt(state.ball).toUpperCase();const d=distance();$('distance').innerHTML=d<20?Math.round(d*3)+' <small>ft to pin</small>':Math.round(d)+' <small>yd to pin</small>';$('wind').textContent='↗ WIND '+Math.round(V.len([wind().x,wind().y])*1.5)+' MPH';$('club').value=state.club;$('power').value=state.power;$('power-value').textContent=Math.round(state.power)+'%';$('carry').textContent='Estimated total: '+Math.round(expected())+' yd';$('swing').disabled=phase==='flight'||state.scores[state.hole]!==null;$('club').disabled=phase!=='aim';$('power').disabled=phase!=='aim';$('swing').innerHTML=phase==='accuracy'?'Strike! <span>●</span>':phase==='flight'?'In flight…':'Swing <span>↗</span>';$('timing').style.display=phase==='accuracy'?'block':'none';$('power').style.display=phase==='accuracy'?'none':'block';$('swing-hint').textContent=phase==='accuracy'?'Stop in the center for a perfect shot':'Click the course to aim';$('accuracy-hint').textContent=phase==='accuracy'?'SPACE TO STRIKE':'SPACE TO SWING';}
function autoClub(){const d=distance(),lie=lieAt(state.ball);state.club=lie==='Green'?6:lie==='Bunker'?5:d>225?0:d>180?1:d>150?2:d>120?3:d>75?4:5;state.power=Math.max(1,Math.min(100,d/(CLUBS[state.club].max*factor())*100));state.angle=Math.atan2(current().green[1]-state.ball[1],current().green[0]-state.ball[0]);}
function setCamera(){const hole=current();let a,b,margin;if(overview){a=[-80,-10];b=[890,750];camera={center:[405,365],angle:0,scale:Math.min(w/1100,(h-120)/850),cx:w*.5,cy:h*.47};return;}const origin=animation?animation.start:state.ball;const d=V.dist(origin,hole.green);if(d<35){a=origin;b=hole.green;margin=48;}else{a=hole.tee;b=hole.green;margin=90;}let center=V.mix(a,b,.5),delta=V.sub(b,a),ang=Math.atan2(delta[1],delta[0])+Math.PI/2,len=V.len(delta);const bottom=w<800?265:190,top=80;const avail=h-bottom-top;let scale=Math.min(avail/(len+margin),w/(Math.max(130,(len+margin)*.75)));camera={center,angle:ang,scale,cx:w*.52,cy:top+avail*.5};}
function screen(p){const d=V.sub(p,camera.center),c=Math.cos(camera.angle),s=Math.sin(camera.angle);return [camera.cx+(d[0]*c+d[1]*s)*camera.scale,camera.cy+(-d[0]*s+d[1]*c)*camera.scale];}
function world(p){const d=[(p[0]-camera.cx)/camera.scale,(p[1]-camera.cy)/camera.scale],c=Math.cos(camera.angle),s=Math.sin(camera.angle);return V.add(camera.center,[d[0]*c-d[1]*s,d[0]*s+d[1]*c]);}
function path(points,color,width){ctx.beginPath();points.forEach((p,i)=>{const s=screen(p);i?ctx.lineTo(...s):ctx.moveTo(...s)});ctx.strokeStyle=color;ctx.lineWidth=width*camera.scale;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();}
function ellipse(p,rx,ry,fill,angle=0,stroke=null){const s=screen(p);ctx.beginPath();ctx.ellipse(s[0],s[1],Math.max(.1,rx*camera.scale),Math.max(.1,ry*camera.scale),angle-camera.angle,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}}
function textAt(p,text,color,size=12){const s=screen(p);ctx.font='600 '+size+'px "DM Sans",sans-serif';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,s[0],s[1]);}
function drawTerrain(time){ctx.fillStyle='#75954c';ctx.fillRect(0,0,w,h);ctx.save();const grad=ctx.createLinearGradient(0,0,w,h);grad.addColorStop(0,'#a3ae62');grad.addColorStop(.3,'#789948');grad.addColorStop(1,'#4f793e');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);
// Native game terrain: fairway meshes and collision surfaces share the same paths.
for(const hole of HOLES){path(hole.path,'#6b9648',58);path(hole.path,'#82ac50',41);ctx.save();ctx.beginPath();hole.path.forEach((p,i)=>{let q=screen(p);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.strokeStyle='#93b65a';ctx.lineWidth=32*camera.scale;ctx.setLineDash([14*camera.scale,14*camera.scale]);ctx.lineCap='butt';ctx.stroke();ctx.restore();}
path(river,'#597b42',37);path(river,'#9aa570',26);path(river,'#326d79',20);path(river,'#538f92',13);for(let i=0;i<river.length-1;i++){let p=V.mix(river[i],river[i+1],.3+(Math.sin(time*.0005+i)*.1));path([p,V.mix(p,river[i+1],.15)],'#a8cbb280',.65);}
for(const dot of grass){const p=screen(dot.p);if(p[0]>0&&p[0]<w&&p[1]>0&&p[1]<h){ctx.fillStyle='#dcdf991f';ctx.fillRect(p[0],p[1],Math.max(1,camera.scale*dot.r),Math.max(1,camera.scale*.5));}}
for(const hole of HOLES){ellipse(hole.green,17,15,'#608e41');ellipse(hole.green,13,11,'#a4c96c',Math.atan2(hole.unit[1],hole.unit[0]),'#aace78');ellipse(V.add(hole.green,[-3,-2]),8,7,'#adcf7333');for(const b of hole.bunkers){ellipse(V.add(b.p,[1,1]),b.rx+1,b.ry+1,'#5d7b40',b.angle);ellipse(b.p,b.rx,b.ry,'#e3d79b',b.angle);ellipse(V.add(b.p,[-1,-1]),b.rx*.75,b.ry*.8,'#eee3b3',b.angle);}ellipse(hole.tee,7,5,'#a0bd67');const side=V.mul(hole.side,4);ellipse(V.add(hole.tee,side),.9,.9,'#f9f2e0');ellipse(V.sub(hole.tee,side),.9,.9,'#f9f2e0');}
// Tree canopies have depth and cast shadows; they also affect shots.
const ordered=trees.map(t=>({...t,s:screen(t.p)})).sort((a,b)=>a.s[1]-b.s[1]);for(const t of ordered){let [x,y]=t.s,r=t.r*camera.scale;if(x< -60||x>w+60||y< -60||y>h+80)continue;ctx.save();ctx.translate(x,y);ctx.fillStyle='#153d2c35';ctx.beginPath();ctx.ellipse(r*.8,r*.5,r*.8,r*1.6,-.7,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#5b5734';ctx.lineWidth=Math.max(1,r*.2);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,-r);ctx.stroke();if(t.tall){for(let j=0;j<3;j++){const size=r*(1-j*.2);ctx.beginPath();ctx.moveTo(0,-r*(3.4-j*.65));ctx.lineTo(-size,-r*(.4+j*.55));ctx.lineTo(size,-r*(.4+j*.55));ctx.closePath();ctx.fillStyle=['#254e36','#32613d','#427a46'][j];ctx.fill();}}else{let gr=ctx.createRadialGradient(-r*.3,-r*1.5,0,0,-r,r*1.15);gr.addColorStop(0,t.color>.5?'#6c994a':'#7ba14e');gr.addColorStop(1,'#315d36');ctx.fillStyle=gr;ctx.beginPath();ctx.arc(0,-r,r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#a6bc5925';ctx.beginPath();ctx.arc(-r*.3,-r*1.3,r*.5,0,Math.PI*2);ctx.fill();}ctx.restore();}
for(const hole of HOLES){const p=screen(hole.green),active=hole===current();ctx.fillStyle='#284c2d';ctx.beginPath();ctx.ellipse(p[0],p[1],Math.max(2,camera.scale*1.3),Math.max(1,camera.scale*.8),0,0,Math.PI*2);ctx.fill();if(active||overview){const pole=Math.max(18,16*camera.scale);ctx.strokeStyle='#fbf7dd';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(...p);ctx.lineTo(p[0],p[1]-pole);ctx.stroke();ctx.fillStyle=active?'#e9f49b':'#f5eee0';ctx.beginPath();ctx.moveTo(p[0],p[1]-pole);ctx.lineTo(p[0]+Math.max(12,pole*.65),p[1]-pole+5);ctx.lineTo(p[0],p[1]-pole+11);ctx.fill();if(overview){ctx.fillStyle='#173e2b';ctx.font='bold 12px sans-serif';ctx.textAlign='left';ctx.fillText(hole.number,p[0]+4,p[1]-pole+5);}}}
ctx.restore();}
function draw(time){ctx.clearRect(0,0,w,h);setCamera();drawTerrain(time);if(trail.length>1)path(trail,'#f2f7c987',1.2);const p=screen(state.ball);if(phase==='aim'&&!overview&&state.scores[state.hole]===null){const target=V.add(state.ball,[Math.cos(state.angle)*expected(),Math.sin(state.angle)*expected()]);const t=screen(target);ctx.save();ctx.setLineDash([5,7]);ctx.strokeStyle='#fcffd99c';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(...p);ctx.lineTo(...t);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#f0ffb5';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(t[0],t[1],12,8,0,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(t[0]-17,t[1]);ctx.lineTo(t[0]+17,t[1]);ctx.moveTo(t[0],t[1]-12);ctx.lineTo(t[0],t[1]+12);ctx.stroke();ctx.font='600 12px "DM Sans",sans-serif';ctx.textAlign='center';const label=Math.round(expected())+' yd';ctx.fillStyle='#173c2be8';ctx.fillRect(t[0]-28,t[1]+15,56,23);ctx.fillStyle='#eff5d0';ctx.fillText(label,t[0],t[1]+31);ctx.restore();}
let z=animation?Math.sin(Math.PI*Math.min(1,animation.t/.78))*CLUBS[animation.club].loft:0;if(animation&&animation.t>.78)z=Math.abs(Math.sin((animation.t-.78)/.22*Math.PI*2))*4*(1-animation.t);z=Math.max(0,z);ctx.fillStyle='#183b2860';ctx.beginPath();ctx.ellipse(p[0]+z*.18,p[1]+3,5+z*.025,2.5,0,0,Math.PI*2);ctx.fill();const by=p[1]-z;ctx.fillStyle='#fffdf0';ctx.shadowColor='#1c342c77';ctx.shadowBlur=3;ctx.beginPath();ctx.arc(p[0],by,Math.max(3.5,Math.min(6,3.2+camera.scale*.2+z*.02)),0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(phase==='aim'){ctx.strokeStyle='#ffffff50';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p[0],p[1],11+Math.sin(time*.003)*2,0,Math.PI*2);ctx.stroke();}
if(overview){ctx.fillStyle='#143b2bdd';ctx.fillRect(w/2-112,h- (w<800?275:195),224,28);ctx.fillStyle='#eaf5cd';ctx.textAlign='center';ctx.font='12px sans-serif';ctx.fillText('COLFAX • NINE-HOLE ROUTING',w/2,h-(w<800?256:176));}}
function startSwing(){if($('modal').open||state.scores[state.hole]!==null||phase==='flight')return;if(overview){overview=false;toast('Hole view restored. Ready to swing.');}if(phase==='aim'){phase='accuracy';needle=0;needleDirection=1;sync();beep(330);}else if(phase==='accuracy'){const error=(needle-.5)*2;shoot(error);}}
function shoot(error){const start=[...state.ball],club=state.club,total=expected(),angle=state.angle+error*(club===6?.08:.14),wd=wind();let finish=V.add(start,[Math.cos(angle)*total,Math.sin(angle)*total]);if(club!==6)finish=V.add(finish,[wd.x*total/220,wd.y*total/220]);else finish=V.add(finish,[Math.sin(state.hole)*total*.015,Math.cos(state.hole)*total*.01]);shotResult=Math.abs(error)<.10?'Perfect strike!':Math.abs(error)<.35?'Solid contact.':error<0?'Pulled left.':'Pushed right.';const tree=trees.find(t=>{const along=V.dist(start,t.p)/Math.max(1,total);return segDist(t.p,start,finish)<t.r*.65&&(club===6||along<.09||along>.88)&&along<1;});if(tree){finish=V.mix(start,tree.p,.86);shotResult='Caught a tree. Find a clear line.';}const landLie=lieAt(finish);if(landLie==='Rough'&&club!==6)finish=V.mix(start,finish,.97);if(landLie==='Bunker'&&club!==6)shotResult='In the sand. The wedge is your friend.';
const hole=current(),near=segDist(hole.green,start,finish);let holed=club===6&&near<1.25&&V.dist(start,finish)>=V.dist(start,hole.green)-.5&&V.dist(finish,hole.green)<5;holed||=V.dist(finish,hole.green)<(club===6?1.4:1.15);if(holed)finish=[...hole.green];state.strokes++;phase='flight';animation={start,end:finish,t:0,club,holed,duration:club===6?1000:1700};trail=[start];beep(800,.10);sync();toast(shotResult,1800);}
function finishShot(){const a=animation;animation=null;const lie=lieAt(state.ball);phase='aim';if(lie==='Water'||lie==='Out of bounds'){state.ball=[...a.start];state.strokes++;trail=[];toast(lie+' · one penalty stroke. Replay from your last lie.',5500);beep(140,.3);}else if(a.holed){state.ball=[...current().green];state.scores[state.hole]=state.strokes;const d=state.strokes-current().par;state.points+=Math.max(0,1000-d*200);save();sync();beep(880,.3);showHoleResult();return;}else{toast(shotResult+' '+Math.round(distance())+' yards remaining.',3800);}if(state.strokes>=12){state.scores[state.hole]=state.strokes;save();sync();showHoleResult(true);return;}autoClub();save();sync();}
function resultName(strokes,par){if(strokes===1)return 'Hole in one!';const n=strokes-par;return n<=-3?'Albatross!':n===-2?'Eagle!':n===-1?'Birdie!':n===0?'Par. Nicely done.':n===1?'Bogey':n===2?'Double bogey':n===3?'Triple bogey':n+' over par';}
function openModal(content){if(phase==='accuracy'){phase='aim';sync();} $('modal-content').innerHTML=content;$('modal').showModal();}
function showHoleResult(limit=false){const end=state.hole===8;openModal('<div class="result"><span class="eyebrow">'+(end?'NINE HOLES IN THE BOOKS':'HOLE '+(state.hole+1)+' COMPLETE')+'</span><h2>'+(limit?'Stroke limit reached':resultName(state.strokes,current().par))+'</h2><div class="big">'+(end?scoreText(toPar()):state.strokes)+'</div><p>'+(end?state.scores.reduce((a,b)=>a+b,0)+' strokes · Par 35 · '+state.points.toLocaleString()+' arcade points':state.strokes+' strokes · Par '+current().par+' · Round '+scoreText(toPar()))+'</p><button class="primary" id="next-hole">'+(end?'View final scorecard':'Next hole →')+'</button></div>');$('next-hole').onclick=()=>{if(end){showScorecard();try{const best=Number(localStorage.getItem('colfax-best'));const n=state.scores.reduce((a,b)=>a+b,0);if(!best||n<best)localStorage.setItem('colfax-best',n);}catch{}return;}$('modal').close();state.hole++;state.ball=[...current().tee];state.strokes=0;trail=[];overview=false;autoClub();save();sync();toast('Hole '+(state.hole+1)+' · '+current().yards+' yards · Par '+current().par,4000);};}
function showScorecard(){const finished=state.scores.every(x=>x!==null);openModal('<span class="eyebrow">COLFAX GOLF COURSE · BLUE / WHITE</span><h2>'+ (finished?'Your round':'Scorecard')+'</h2><table><thead><tr><th>HOLE</th><th>YARDS</th><th>PAR</th><th>STROKES</th><th>+/−</th></tr></thead><tbody>'+HOLES.map((h,i)=>'<tr class="'+(i===state.hole?'current':'')+'"><td>'+h.number+'</td><td>'+h.yards+'</td><td>'+h.par+'</td><td>'+(state.scores[i]??(i===state.hole&&state.strokes?state.strokes+'*':'—'))+'</td><td>'+(state.scores[i]===null?'—':scoreText(state.scores[i]-h.par))+'</td></tr>').join('')+'<tr class="total"><td>TOTAL</td><td>3,010</td><td>35</td><td>'+state.scores.reduce((a,b)=>a+(b??0),0)+'</td><td>'+scoreText(toPar())+'</td></tr></tbody></table><p class="source-note">'+(finished?'Round complete. '+state.points.toLocaleString()+' arcade points.':'* Hole in progress. Totals count completed holes. Your round saves automatically on this device.')+'</p><button class="primary" id="round-action">'+(finished?'Play another round':state.scores[state.hole]!==null?'Continue to next hole':'Back to course')+'</button><p><button id="restart">Start a new round</button></p>');$('round-action').onclick=()=>{if(finished)newRound();else if(state.scores[state.hole]!==null){$('modal').close();state.hole++;state.strokes=0;state.ball=[...current().tee];trail=[];autoClub();save();sync();}else $('modal').close();};$('restart').onclick=()=>{openModal('<h2>Start a new round?</h2><p>This will replace your current round on this device.</p><button class="primary" id="confirm-restart">Start new round</button>');$('confirm-restart').onclick=newRound;};}
function newRound(){state={hole:0,ball:[...HOLES[0].tee],strokes:0,scores:Array(9).fill(null),club:0,power:95,angle:0,points:0};phase='aim';animation=null;trail=[];overview=false;autoClub();save();sync();$('modal').close();toast('A fresh nine. Make it count.',4000);}
$('club').onchange=e=>{if(phase!=='aim')return;state.club=Number(e.target.value);sync();};$('power').oninput=e=>{if(phase!=='aim')return;state.power=Number(e.target.value);sync();};$('swing').onclick=startSwing;$('pin').onclick=()=>{if(phase!=='aim')return;autoClub();sync();toast('Aimed at the pin. Allow for the wind.');};$('overview').onclick=()=>{overview=!overview;$('overview').setAttribute('aria-pressed',overview);};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',sound);beep();};$('scorecard').onclick=showScorecard;$('close-modal').onclick=()=>$('modal').close();$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('modal').close();}});
$('help').onclick=()=>openModal('<span class="eyebrow">SINGLE PLAYER · NINE HOLES</span><h2>A little timing.<br>A lot of golf.</h2><div class="info-list"><b>01</b><p><strong>Pick your line.</strong> Click or tap the course to aim. Your power adjusts to the target, up to your club’s range. Use “Aim at pin” for an automatic club and line.</p><b>02</b><p><strong>Choose your shot.</strong> Select a club and adjust the power slider. The dotted line shows your estimated distance before wind and swing error.</p><b>03</b><p><strong>Time the strike.</strong> Click Swing, then click Strike when the moving marker reaches the pale center. Or press <kbd>Space</kbd> twice.</p><b>04</b><p><strong>Finish at the cup.</strong> A putter is selected on the green. Rough reduces distance, bunkers favor a wedge, and trees can block low shots. Water and out-of-bounds add one stroke and return the ball to its previous lie.</p></div><p><kbd>←</kbd> <kbd>→</kbd> aim · <kbd>↑</kbd> <kbd>↓</kbd> power · <kbd>Esc</kbd> cancel swing. Complete all nine holes in as few strokes as possible. Arcade scoring has a 12-stroke limit per hole and generous cup capture.</p>');
$('about').onclick=()=>openModal('<span class="eyebrow">THE REAL COURSE BEHIND THE GAME</span><h2>Colfax, Washington.</h2><p>A playable arcade recreation of Colfax’s nine-hole, par-35 course beside the North Palouse River.</p><p><strong>Grounded in sources:</strong> hole numbers, pars and published Blue/White yardages; tee and green positions from GolfTraxx’s mapped coordinates; wooded river-valley character from the club’s aerial photograph and course description.</p><p><strong>Approximated for play:</strong> fairway outlines, river banks, bunker shapes, tree positions, green contours and ball physics. This is not a surveyed digital twin or an official club product.</p><p>Facebook’s public listing was found, but the page blocked access. Google Earth was attempted but could not render without WebGL in the research browser. No Google Earth imagery was imported.</p><ul><li><a href="https://colfaxgolfclub.com/the-golf-course" target="_blank" rel="noopener">Official course description and aerial flyover</a></li><li><a href="https://colfaxgolfclub.com/" target="_blank" rel="noopener">Club gallery and aerial photograph</a></li><li><a href="https://golftraxx.com/full-layout?city=Colfax&coursename=Colfax+Golf+Club&state=WA&static=true&zipcode=99111" target="_blank" rel="noopener">GolfTraxx mapped routing</a></li><li><a href="https://www.golflink.com/golf-courses/wa/colfax/colfax-golf-club" target="_blank" rel="noopener">Published hole-by-hole scorecard</a></li><li><a href="https://www.facebook.com/colfaxgolfcourse/" target="_blank" rel="noopener">Club’s Facebook page</a></li></ul><p class="source-note">Research: September 7, 2026. Your round is stored only in this browser.</p>');
canvas.addEventListener('pointerdown',e=>{if(phase==='accuracy'){startSwing();return;}if(phase!=='aim'||overview||state.scores[state.hole]!==null)return;const r=canvas.getBoundingClientRect(),p=world([e.clientX-r.left,e.clientY-r.top]),d=V.sub(p,state.ball);if(V.len(d)<1)return;state.angle=Math.atan2(d[1],d[0]);state.power=Math.max(1,Math.min(100,V.len(d)/CLUBS[state.club].max/factor()*100));sync();});
document.addEventListener('keydown',e=>{if($('modal').open)return;if(['INPUT','SELECT'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();if(!e.repeat)startSwing();}if(e.code==='Escape'&&phase==='accuracy'){phase='aim';sync();}if(phase==='aim'){if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.code==='ArrowLeft')state.angle-=.015;if(e.code==='ArrowRight')state.angle+=.015;if(e.code==='ArrowUp')state.power=Math.min(100,state.power+1);if(e.code==='ArrowDown')state.power=Math.max(1,state.power-1);sync();}});
function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);setCamera();}window.addEventListener('resize',resize);
function frame(now){const dt=Math.min(now-lastTime,40)||16;lastTime=now;if(!$('modal').open&&phase==='accuracy'){needle+=dt*.00085*needleDirection;if(needle>=1){needle=1;needleDirection=-1;}if(needle<=0){needle=0;needleDirection=1;}$('needle').style.left=(needle*100)+'%';}if(animation){animation.t=Math.min(1,animation.t+dt/animation.duration);const t=animation.t,progress=t<.78?(t/.78)*.93:.93+.07*(1-(1-(t-.78)/.22)**2);state.ball=V.mix(animation.start,animation.end,progress);if(trail.length===0||V.dist(trail[trail.length-1],state.ball)>3)trail.push([...state.ball]);if(t>=1){state.ball=[...animation.end];finishShot();}}draw(now);if(now>toastUntil)$('toast').style.opacity='0';requestAnimationFrame(frame);}
resize();sync();requestAnimationFrame(frame);if(state.scores[state.hole]!==null)showHoleResult();
